name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Stop Existing Container
        run: |
          docker stop webapp || true
          docker rm webapp || true

      - name: Build Docker Image
        run: |
          docker build -t simple-webapp .

      - name: Run Docker Container
        run: |
          docker run -d \
            --name webapp \
            -p 3000:3000 \
            simple-webapp